--- 
apiVersion: v1
kind: ReplicationController
metadata: 
  name: myapp-rc2
spec: 
   replicas: 5  
   selector:    
     app: myapp    
     zone: prod           
     version: v2 
   template:    
     metadata:         
       labels:           
         app: myapp           
         zone: prod           
         version: v2        
     spec:           
       containers:             
         - name: myapp-frontendmvc              
           image: makader/myapp:frontendmvc-v2              
           ports:               
             - containerPort: 80