--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp-deployment
spec: 
   replicas: 3  
   selector:    
     matchLabels:
       app: myapp
   template:    
     metadata:         
       labels:           
         app: myapp           
         zone: prod           
         version: v1        
     spec:           
       containers:             
         - name: myapp-frontendmvc              
           image: makader/myapp:frontendmvc-v1              
           ports:               
             - containerPort: 80