version: '3'
services:
  frontendmvc:
     build:
       ./frontendmvc
       dockerfile: Prod.Dockerfile
     ports:
       - 5000:5000
       - 5001:5001
     depends_on:
       - ss2017withoutmount
  ss2017withoutmount:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Sample123!"
