--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp-deployment
spec: 
   replicas: 10 
   selector:    
     matchLabels:
       app: myapp
   minReadySeconds: 5 
   strategy:
     type: RollingUpdate 
     rollingUpdate:
       maxSurge: 1 
       maxUnavailable: 1       
   template:    
     metadata:         
       labels:           
         app: myapp           
         zone: prod           
         version: v1        
     spec:           
       containers:             
         - name: myapp-frontendmvc              
           image: makader/myapp:frontendmvc-v1              
           ports:               
             - containerPort: 80